services:
  interface:
    image: qbioturin/insite_interface:0.1.0
    restart: unless-stopped
    networks:
      - cancersimulation-network
    ports:
      - "3000:3000"

  simulator:
    image: qbioturin/insite_simulator:0.1.0
    restart: unless-stopped
    networks:
      - cancersimulation-network

networks:
  cancersimulation-network:
    driver: bridge