services:
  interface:
    build:
      context: interface
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - cancersimulation-network
    ports:
      - "3000:3000"

  simulator:
    build:
      context: simulator
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - cancersimulation-network
    volumes:
      - './simulator/data:/data'

networks:
  cancersimulation-network:
    driver: bridge