import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';
import { MantineProvider } from '@mantine/core';
import AppShellLayout from "@/components/app-shell";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html >
			<body>
				<MantineProvider>
					<AppShellLayout>{children}</AppShellLayout>
				</MantineProvider>
			</body>
		</html>
	);
}
